const app=document.getElementById("app");

const tenders=[
 {id:"GEM-SSL-2026-041",title:"Metro Smart Lighting — Integrated Supply & Installation",department:"Urban Infrastructure Procurement",value:"₹20 Cr",bids:3,highRisk:1,status:"ACTIVE",compliance:86,checks:"28/30",queue:2,summary:"Main showcase case with a high-risk bidder and multiple evidence-backed indicators.",
  bidders:[
   {id:"BID-A",name:"Apex Infra Systems Pvt. Ltd.",compliance:100,risk:8,level:"LOW",rec:"PROCEED",price:"₹19,82,400",flags:[],req:[
    ["Udyam / MSME","VERIFIED","Udyam"],["GST","VERIFIED","GSTN"],["Turnover","VERIFIED","Income Tax"],["Experience","VERIFIED","Bid"],["OEM Authorization","VERIFIED","OEM/BIS"],["Blacklist","CLEAR","Debarment"],["Local Content","VERIFIED","Bid"]]},
   {id:"BID-B",name:"Bharat Urban Tech Ltd.",compliance:86,risk:39,level:"MEDIUM",rec:"REVIEW",price:"₹19,83,100",flags:[
    {level:"MEDIUM",title:"Last-minute compliance correction",reason:"Two missing filings were corrected shortly before the tender deadline.",evidence:["Correction: 10 Sep 2026","Tender deadline: 15 Sep 2026"]}],req:[
    ["Udyam / MSME","VERIFIED","Udyam"],["GST","VERIFIED","GSTN"],["Turnover","VERIFIED","Income Tax"],["Experience","VERIFIED","Bid"],["OEM Authorization","VERIFIED","OEM/BIS"],["Blacklist","CLEAR","Debarment"],["Local Content","VERIFIED","Bid"]]},
   {id:"BID-C",name:"CivicGrid Solutions Pvt. Ltd.",compliance:72,risk:91,level:"HIGH",rec:"HUMAN REVIEW REQUIRED",price:"₹19,82,950",flags:[
    {level:"HIGH",title:"Turnover mismatch",reason:"Declared turnover is higher than the controlled verified financial record.",evidence:["Declared: ₹12.4 Cr","Verified: ₹7.1 Cr","Difference: ₹5.3 Cr"]},
    {level:"HIGH",title:"Potential bidder relationship",reason:"A common director is present between Bharat Urban and CivicGrid.",evidence:["Bharat Urban ↔ CivicGrid","Signal: common director"]},
    {level:"MEDIUM",title:"Similar bid prices",reason:"Submitted prices are unusually close and warrant human review.",evidence:["A: ₹19,82,400","B: ₹19,83,100","C: ₹19,82,950"]},
    {level:"MEDIUM",title:"Document similarity indicator",reason:"Formatting and repeated metadata patterns match another bidder submission.",evidence:["Similarity cluster: Bharat Urban ↔ CivicGrid"]}],req:[
    ["Udyam / MSME","VERIFIED","Udyam"],["GST","VERIFIED","GSTN"],["Turnover","MISMATCH","Income Tax"],["Experience","VERIFIED","Bid"],["OEM Authorization","VERIFIED","OEM/BIS"],["Blacklist","CLEAR","Debarment"],["Local Content","VERIFIED","Bid"]]}
 ]},
 {id:"GEM-ROAD-2026-018",title:"Smart Road Maintenance & Monitoring",department:"Public Works Department",value:"₹8.5 Cr",bids:5,highRisk:0,status:"UNDER REVIEW",compliance:91,checks:"46/50",queue:1,summary:"Medium-risk case showing a normal compliance review workflow.",
  bidders:[
   {id:"ROAD-A",name:"RoadTech Engineering Pvt. Ltd.",compliance:97,risk:12,level:"LOW",rec:"PROCEED",price:"₹8,21,00,000",flags:[],req:[["GST","VERIFIED","GSTN"],["Turnover","VERIFIED","Income Tax"],["Experience","VERIFIED","Bid"],["Equipment","VERIFIED","Bid"],["Debarment","CLEAR","Debarment"]]},
   {id:"ROAD-B",name:"UrbanRoute Infra Ltd.",compliance:91,risk:42,level:"MEDIUM",rec:"REVIEW",price:"₹8,24,50,000",flags:[{level:"MEDIUM",title:"Experience document needs review",reason:"One supporting project certificate needs manual confirmation.",evidence:["Certificate reference: UR-EXP-22","Status: manual review"]}],req:[["GST","VERIFIED","GSTN"],["Turnover","VERIFIED","Income Tax"],["Experience","REVIEW","Bid"],["Equipment","VERIFIED","Bid"],["Debarment","CLEAR","Debarment"]]},
   {id:"ROAD-C",name:"Civic Roads & Mobility",compliance:84,risk:58,level:"MEDIUM",rec:"REVIEW",price:"₹8,22,80,000",flags:[{level:"MEDIUM",title:"Bid price deviation",reason:"Price is close to another submission and should be reviewed with the tender context.",evidence:["UrbanRoute: ₹8.24 Cr","Civic Roads: ₹8.228 Cr"]}],req:[["GST","VERIFIED","GSTN"],["Turnover","VERIFIED","Income Tax"],["Experience","VERIFIED","Bid"],["Equipment","REVIEW","Bid"],["Debarment","CLEAR","Debarment"]]}
 ]},
 {id:"GEM-SOLAR-2026-072",title:"Solar Street Infrastructure",department:"Renewable Energy Department",value:"₹11 Cr",bids:4,highRisk:0,status:"ACTIVE",compliance:98,checks:"38/40",queue:0,summary:"Low-risk clean case demonstrating that the system can clear compliant procurement.",
  bidders:[
   {id:"SOL-A",name:"SunGrid Energy Pvt. Ltd.",compliance:99,risk:5,level:"LOW",rec:"PROCEED",price:"₹10,72,00,000",flags:[],req:[["GST","VERIFIED","GSTN"],["Turnover","VERIFIED","Income Tax"],["Experience","VERIFIED","Bid"],["OEM Authorization","VERIFIED","OEM/BIS"],["Debarment","CLEAR","Debarment"]]},
   {id:"SOL-B",name:"GreenBeam Infrastructure",compliance:98,risk:9,level:"LOW",rec:"PROCEED",price:"₹10,79,50,000",flags:[],req:[["GST","VERIFIED","GSTN"],["Turnover","VERIFIED","Income Tax"],["Experience","VERIFIED","Bid"],["OEM Authorization","VERIFIED","OEM/BIS"],["Debarment","CLEAR","Debarment"]]},
   {id:"SOL-C",name:"EcoVolt Systems",compliance:96,risk:14,level:"LOW",rec:"PROCEED",price:"₹10,81,00,000",flags:[],req:[["GST","VERIFIED","GSTN"],["Turnover","VERIFIED","Income Tax"],["Experience","VERIFIED","Bid"],["OEM Authorization","VERIFIED","OEM/BIS"],["Debarment","CLEAR","Debarment"]]},
   {id:"SOL-D",name:"SolarWorks India",compliance:97,risk:11,level:"LOW",rec:"PROCEED",price:"₹10,76,00,000",flags:[],req:[["GST","VERIFIED","GSTN"],["Turnover","VERIFIED","Income Tax"],["Experience","VERIFIED","Bid"],["OEM Authorization","VERIFIED","OEM/BIS"],["Debarment","CLEAR","Debarment"]]}
 ]}
];

const sources=["Udyam","GSTN","Income Tax","MCA21","EPFO / ESIC","DigiLocker","Startup India","NSIC","OEM / BIS / DPIIT","Debarment"];
let page="select", tenderIndex=0, selectedIndex=2;
const audit=[["09:31:12","SYSTEM","Tender portfolio loaded","a91c...41e"],["09:32:03","SYSTEM","3 procurement tenders available","c13f...9aa"],["09:32:44","AI ENGINE","Tender requirements normalized","d42b...e17"],["09:32:58","VERIFICATION","Source checks completed","6fe1...b12"],["09:33:07","RISK ENGINE","High-risk indicators detected for CivicGrid","7be1...2c0"]];


function portalTop(){
  return `<div class="portal-strip"><div><b>ClearBid Procurement Trust Layer</b> &nbsp; | &nbsp; AI-assisted public procurement assurance</div><div>🔒 Secure Portal &nbsp; • &nbsp; System Operational &nbsp; • &nbsp; Last sync: Today, 09:32 AM</div></div>
  <div class="utility-bar"><span>Government Procurement Technology</span><div><button>Help</button><button>Accessibility</button><button>Notifications <b class="notif">2</b></button><button class="userbox">Procurement Officer ▾</button></div></div>`;
}
function hero(){
  return `<div class="hero">
    <div class="hero-slides">
      <div class="hero-slide active"><div class="hero-copy"><div class="hero-kicker">AI-ASSISTED PROCUREMENT ASSURANCE</div><h2>Verify. Detect. Explain.<br><span>Decide with confidence.</span></h2><p>Cross-source bidder verification with explainable risk indicators and evidence-backed review.</p><div class="hero-buttons"><button class="hero-btn" onclick="go('verification')">Explore Verification →</button><button class="hero-link" onclick="go('fraud')">View Risk Signals</button></div></div></div>
      <div class="hero-slide"><div class="hero-copy"><div class="hero-kicker">EARLY RISK DETECTION</div><h2>Find anomalies<br><span>before approval.</span></h2><p>Surface financial mismatches, unusual bid similarity and relationship indicators for officer investigation.</p><div class="hero-buttons"><button class="hero-btn" onclick="go('fraud')">Open Forensics →</button><button class="hero-link" onclick="go('graph')">View Risk Graph</button></div></div></div>
      <div class="hero-slide"><div class="hero-copy"><div class="hero-kicker">HUMAN-IN-THE-LOOP GOVERNANCE</div><h2>AI recommends.<br><span>Officers decide.</span></h2><p>High-risk actions require justification, review safeguards and a traceable audit trail.</p><div class="hero-buttons"><button class="hero-btn" onclick="go('governance')">Open Governance →</button><button class="hero-link" onclick="go('audit')">View Audit Trail</button></div></div></div>
    </div>
    <div class="hero-art"><div class="grid-lines"></div><div class="orb o1"></div><div class="orb o2"></div><div class="shield">✓</div><div class="art-card ac1">✓ <b>Verified</b><small>Cross-source checks</small></div><div class="art-card ac2">⚠ <b>Risk 91/100</b><small>Human review required</small></div><div class="art-card ac3">▣ <b>Evidence</b><small>Traceable audit record</small></div></div>
    <div class="slider-nav"><button onclick="heroSlide(0)">01</button><button onclick="heroSlide(1)">02</button><button onclick="heroSlide(2)">03</button></div>
  </div>`;
}
function heroSlide(i){document.querySelectorAll(".hero-slide").forEach((x,n)=>x.classList.toggle("active",n===i));document.querySelectorAll(".slider-nav button").forEach((x,n)=>x.classList.toggle("active",n===i));}
function quickTiles(){
 return `<div class="quick-section"><div class="section-title"><div><h2>Quick Access</h2><small>Key procurement assurance services</small></div></div><div class="quick-tiles">
 <div class="qtile" onclick="go('dashboard')"><div class="qticon">▦</div><div><b>Tender Command Center</b><small>${tenders.length} active demonstration tenders</small></div><span>→</span></div>
 <div class="qtile" onclick="go('verification')"><div class="qticon">✓</div><div><b>Bid Verification</b><small>Cross-source compliance checks</small></div><span>→</span></div>
 <div class="qtile" onclick="go('fraud')"><div class="qticon">⚠</div><div><b>Risk & Forensics</b><small>Explainable anomaly indicators</small></div><span>→</span></div>
 <div class="qtile" onclick="go('governance')"><div class="qticon">⚖</div><div><b>Human Governance</b><small>Officer decision & safeguards</small></div><span>→</span></div>
 </div></div>`;
}

function T(){return tenders[tenderIndex]}
function B(){return T().bidders[selectedIndex]||T().bidders[0]}
function tone(x){return x==="LOW"?"low":x==="MEDIUM"?"medium":x==="HIGH"?"high":"gray"}
function pill(x,c){return `<span class="pill ${c||tone(x)}">${x}</span>`}
function go(x){page=x;render()}
function selectTender(i){tenderIndex=i;selectedIndex=0;page="dashboard";render()}
function backToTenders(){page="select";render()}
function selectBidder(i){selectedIndex=i;page="verification";render()}
function nav(name,icon,target){return `<button class="nav ${page===target?"active":""}" onclick="go('${target}')"><span>${icon}</span>${name}</button>`}
function sidebar(){return `<aside class="sidebar"><div class="gov-strip"><span>Government Procurement Technology</span><span>Secure • Transparent • Auditable</span></div><div class="portal-head"><div class="logo"><span>✓</span><div><b>ClearBid</b><small>Procurement Trust Layer</small></div></div><div class="portal-actions"><span>Help</span><span>Notifications</span><b>Procurement Officer ▾</b></div></div><div class="portal-nav"><div class="nav-title">WORKSPACE</div>${nav("Command Center","▦","select")}${nav("Tender & Bid Intake","↑","intake")}${nav("Verification Center","✓","verification")}${nav("Fraud & Forensics","◈","fraud")}${nav("Risk / Collusion Graph","◎","graph")}${nav("Rule Governance","⚙","rules")}${nav("Officer Accountability","⚖","governance")}${nav("Audit Trail","▣","audit")}</div><div class="bottom">● System operational &nbsp; | &nbsp; AI-assisted · Human-governed</div></aside>`}
function header(){return `<div class="header"><div><div class="breadcrumb">Home / Procurement Evaluation / ${page==="select"?"Tender Selection":page.charAt(0).toUpperCase()+page.slice(1)}</div><div class="small">CLEARBID · AI-ASSISTED PROCUREMENT TRUST LAYER</div><h1>${page==="select"?"Tender Command Center":T().title}</h1><div class="small">${page==="select"?"Select a tender to begin AI-assisted verification and risk analysis":T().id+" · "+T().department+" · "+T().value}</div></div><div class="session"><span>Evaluation Session</span><b>ACTIVE</b><small>Last sync: Just now</small></div></div>`}
function tenderCards(){return `<div class="selection-intro"><div><div class="smallcaps">PROCUREMENT WORKSPACE</div><h2>Select a tender to evaluate</h2><p class="small">Choose one tender to open its complete verification, risk, fraud and governance workspace.</p></div><div class="selection-count"><strong>${tenders.length}</strong><span>demo tenders</span></div></div><div class="tender-list">${tenders.map((t,i)=>`<div class="card tender-row"><div class="tender-id">${String(i+1).padStart(2,"0")}</div><div class="tender-main"><div class="tender-top"><div class="smallcaps">${t.id}</div>${pill(t.highRisk?"HIGH RISK":t.status==="UNDER REVIEW"?"MEDIUM RISK":"LOW RISK")}</div><h2>${t.title}</h2><div class="tender-meta">${t.department}</div><div class="tender-details"><span><b>Value</b>${t.value}</span><span><b>Bids</b>${t.bids}</span><span><b>Compliance</b>${t.compliance}%</span><span><b>Status</b>${t.status}</span></div></div><div class="tender-action"><button class="btn primary" onclick="selectTender(${i})">Open Analysis →</button><small>View bidders & risk</small></div></div>`).join("")}</div>`}
function selectedSummary(){let t=T();return `<div class="card summary"><div><div class="smallcaps">SELECTED TENDER</div><strong>${t.title}</strong><div class="small">${t.id} · ${t.summary}</div></div><div><small>BIDS</small><strong>${t.bids}</strong></div><div><small>HIGH RISK</small><strong class="${t.highRisk?"red":""}">${t.highRisk}</strong></div><div><small>REVIEW QUEUE</small><strong class="yellow">${t.queue}</strong></div><div><small>STATUS</small><strong class="green">${t.status}</strong></div></div>`}
function dashboard(){return `<div class="backbar"><button class="btn" onclick="backToTenders()">← Back to Tender Selection</button><span class="small">Selected tender · ${T().id}</span></div>${selectedSummary()}<div class="cards"><div class="card metric"><small>Requirement compliance</small><strong>${T().compliance}%</strong><span class="small">selected tender average</span></div><div class="card metric"><small>Source checks</small><strong>${T().checks}</strong><span class="small">verification records</span></div><div class="card metric"><small>Review queue</small><strong class="yellow">${T().queue}</strong><span class="small">bids need attention</span></div><div class="card metric"><small>Audit coverage</small><strong>100%</strong><span class="small">actions logged</span></div></div>
<div class="card"><div class="head"><div><h2>Bidder risk overview</h2><small>${T().id} · compliance and explainable risk</small></div><button class="btn" onclick="go('verification')">Verification Center →</button></div><div class="bidcards">${T().bidders.map((b,i)=>`<div class="bid" onclick="selectBidder(${i})"><div class="bidtop"><div class="company"><div class="avatar">${b.name[0]}</div><div><b>${b.name}</b><small>${b.id} · ${b.price}</small></div></div>${pill(b.level)}</div><div class="bidstats"><div><small>COMPLIANCE</small><strong>${b.compliance}%</strong><div class="bar"><i style="width:${b.compliance}%"></i></div></div><div><small>RISK SCORE</small><strong class="${b.risk>70?"red":b.risk>30?"yellow":"green"}">${b.risk}/100</strong><div class="bar risk"><i style="width:${b.risk}%"></i></div></div></div><div class="bidfoot"><span>${b.rec}</span><span>Inspect →</span></div></div>`).join("")}</div></div>
<div class="two"><div class="card"><div class="head"><div><h2>Priority alerts</h2><small>Risk indicators for selected tender</small></div>${pill(T().highRisk?"HIGH":"MONITOR")}</div>${T().bidders.flatMap(b=>b.flags.map(f=>`<div class="alert"><div class="alert-icon">!</div><div><b>${f.title}</b><small>${b.name}: ${f.reason}</small></div></div>`)).slice(0,4).join("")||`<div class="empty">No material risk indicators in this tender. ClearBid can recommend proceeding when evidence is clean.</div>`}</div><div class="card"><div class="head"><div><h2>Quick actions</h2><small>Demo navigation</small></div></div><div class="quick"><div><b>Inspect selected bid</b><button class="btn primary" onclick="go('verification')">Open</button></div><div><b>Evidence chain</b><button class="btn" onclick="evidence()">Why?</button></div><div><b>Risk graph</b><button class="btn" onclick="go('graph')">Open</button></div><div><b>Officer governance</b><button class="btn" onclick="go('governance')">Open</button></div></div></div></div>`}
function intake(){return `<div class="notice"><b>Prototype workflow:</b> upload a tender and bidder documents → extract requirements → verify claims → calculate risk. Current demo uses controlled sample data.</div><div class="cards"><div class="card" style="padding:14px"><div class="smallcaps">01 · TENDER</div><h2 style="font-size:14px">Upload tender</h2><p class="small">Production: OCR + NLP/LLM extracts procurement requirements.</p><input type="file" accept=".pdf,.doc,.docx"><button class="btn primary" style="margin-top:8px" onclick="processDemo()">Process tender</button></div><div class="card" style="padding:14px"><div class="smallcaps">02 · BID DOCUMENTS</div><h2 style="font-size:14px">Upload bidder documents</h2><p class="small">Certificates, declarations and financial documents.</p><input type="file" multiple accept=".pdf,.doc,.docx,.jpg,.png"><button class="btn primary" style="margin-top:8px" onclick="processDemo()">Process documents</button></div><div class="card" style="padding:14px"><div class="smallcaps">03 · PIPELINE</div><h2 style="font-size:14px">Processing</h2><p id="processMsg" class="small">Ready.</p><div style="margin-top:10px;font-size:9px;line-height:2">✓ OCR / extraction<br>✓ Normalize requirements<br>✓ Map bidder fields<br>✓ Send to verification</div></div><div class="card" style="padding:14px"><div class="smallcaps">04 · OUTPUT</div><h2 style="font-size:14px">Normalized requirements</h2><div style="font-size:9px;line-height:2">✓ Turnover<br>✓ Experience<br>✓ Valid GST<br>✓ OEM authorization<br>✓ No debarment<br>✓ Local content<br>✓ MSME / Udyam</div></div></div>`}
function verification(){let b=B();return `<div class="layout"><div class="card list"><div class="head"><div><h2>Bid submissions</h2><small>${T().id}</small></div></div>${T().bidders.map((x,i)=>`<button class="${i===selectedIndex?"active":""}" onclick="selectBidder(${i})"><div class="avatar">${x.name[0]}</div><div style="flex:1"><b>${x.name}</b><small>${x.id}</small></div>${pill(x.level)}</button>`).join("")}</div><div class="content"><div class="card profile"><div class="avatar">${b.name[0]}</div><div class="grow"><div class="smallcaps">BIDDER ASSESSMENT</div><h2>${b.name}</h2><small>${b.id} · ${b.price}</small></div><div class="score"><strong class="${tone(b.level)}">${b.risk}</strong><small>risk /100</small></div><div class="score"><strong>${b.compliance}%</strong><small>compliance</small></div></div><div class="card toolbar"><small>${pill(b.level)} · ${b.rec} · AI recommendation is advisory.</small><div class="actions"><button class="btn" onclick="evidence()">Why / Evidence</button><button class="btn" onclick="go('fraud')">Forensics</button><button class="btn" onclick="go('graph')">Graph</button></div></div><div class="card rows" style="margin-top:7px"><div class="head"><div><h2>Requirement verification</h2><small>Tender rule → bidder claim → source result</small></div></div>${b.req.map((r,i)=>`<div class="row"><div class="check ${r[1]==="MISMATCH"||r[1]==="REVIEW"?"bad":"ok"}">${r[1]==="MISMATCH"?"×":r[1]==="REVIEW"?"!":"✓"}</div><div><b>${r[0]}</b><small>Source: ${r[2]}</small></div>${pill(r[1],r[1]==="MISMATCH"||r[1]==="REVIEW"?"high":"low")}<div>${r[1]==="MISMATCH"||r[1]==="REVIEW"?`<button class="btn" onclick="evidence()">Why?</button>`:""}</div></div>`).join("")}</div><div class="card" style="margin-top:7px"><div class="head"><div><h2>Source verification</h2><small>Controlled/mock adapters for prototype</small></div></div><div class="sources">${sources.map(s=>{let st="VERIFIED",cl="low";if(T().id==="GEM-SSL-2026-041"&&b.id==="BID-C"&&s==="Income Tax"){st="MISMATCH";cl="high"}if((b.level==="MEDIUM"&&s==="MCA21")){st="REVIEW FLAG";cl="medium"}if(s==="Debarment")st="CLEAR";return `<div class="source"><div><b>${s}</b><small>Verification adapter</small></div>${pill(st,cl)}</div>`}).join("")}</div><div class="evidencebar"><div><b>Evidence chain available</b><small>Requirement → claim → verified record → indicator</small></div><button class="btn primary" onclick="evidence()">Open Evidence</button></div></div><div class="card toolbar"><small>Final decision remains with authorized officer.</small><div class="actions"><button class="btn" onclick="record('RAISE QUERY')">Query</button><button class="btn redbtn" onclick="record('DISQUALIFY')">Disqualify</button><button class="btn primary" onclick="approve()">Approve</button></div></div></div></div>`}
function fraud(){let b=B();return `<div class="fraud"><div class="card"><div class="head"><div><div class="smallcaps">INTELLIGENCE LAYER</div><h2>Fraud & anomaly indicators</h2><small>Signals support investigation; they are not proof.</small></div>${pill(b.level)}</div><div class="risk"><span>Explainable risk score</span><strong class="${b.risk>70?"red":b.risk>30?"yellow":"green"}">${b.risk}/100</strong><div class="riskbar"><i style="width:${b.risk}%"></i></div><small class="small">Mismatch 40% · Relationship 25% · Price similarity 20% · Document forensics 15%</small></div>${b.flags.length?b.flags.map(f=>`<div class="flag">${pill(f.level)}<div><b>${f.title}</b><p>${f.reason}</p></div><button class="btn" onclick="evidence()">Evidence</button></div>`).join(""):`<div class="empty">No material fraud/anomaly indicators detected for this selected bidder.</div>`}</div><div class="card weights"><h2>Risk model</h2><p class="small">Weighted indicators keep the prototype explainable.</p>${[["Cross-source mismatch","40%"],["Relationship indicators","25%"],["Bid-price similarity","20%"],["Document forensics","15%"]].map(x=>`<div class="weight">${x[0]} <strong>${x[1]}</strong></div>`).join("")}<p style="font-size:8px;color:#69778a;background:#f1f5f8;padding:8px">HIGH RISK means human review is required. It does not establish fraud.</p></div></div>`}
function graph(){let b=B();return `<div class="layout"><div class="card"><div class="head"><div><h2>Risk / Collusion Graph</h2><small>${T().title} · potential relationships and similarity indicators</small></div>${pill(b.level,"high")}</div><div class="graph"><div class="line l1"></div><div class="line l2"></div><div class="line l3"></div><div class="node a" style="left:25%;top:53%"><div class="circle">A</div><label>${T().bidders[0]?.name||"Bidder A"}</label></div><div class="node b" style="left:50%;top:28%"><div class="circle">B</div><label>${T().bidders[1]?.name||"Bidder B"}</label></div><div class="node c" style="left:76%;top:67%"><div class="circle">C</div><label>${T().bidders[2]?.name||"Bidder C"}</label></div></div></div><div class="card"><div class="head"><div><h2>Detected signals</h2><small>Investigation indicators</small></div></div>${T().id==="GEM-SSL-2026-041"?`<div class="signal">${pill("HIGH")}<div><b>Common director</b><small>Bharat Urban ↔ CivicGrid</small></div></div><div class="signal">${pill("MEDIUM")}<div><b>Similar bid prices</b><small>Three prices are unusually close</small></div></div><div class="signal">${pill("MEDIUM")}<div><b>Document similarity</b><small>Bharat Urban ↔ CivicGrid</small></div></div>`:`<div class="signal">${pill("LOW")}<div><b>No strong relationship signal</b><small>Graph shown as a demonstration of cross-bidder analysis.</small></div></div>`}</div></div>`}
function rules(){return `<div class="card rules"><div class="head"><div><div class="smallcaps">RULE GOVERNANCE</div><h2>AI-proposed rule updates</h2><small>Admin approval is required before activation.</small></div></div><div class="rule"><div class="ruleicon">⚙</div><div><b>MSME investment threshold update</b><small>RU-017 · Mock Gazette Circular 2026/17</small><p>₹1 Cr → ₹2.5 Cr · Proposed effective date: 01 Oct 2026</p></div><div><button class="btn" onclick="ruleAction('REJECT')">Reject</button> <button class="btn primary" onclick="ruleAction('APPROVE')">Approve</button></div></div><div class="rule"><div class="ruleicon">✓</div><div><b>Local content declaration wording</b><small>RU-016 · Mock Procurement Circular 2026/11</small><p>Version 2.1 → Version 2.2 · Effective: 20 Sep 2026</p></div>${pill("APPROVED","low")}</div></div>`}
function governance(){let b=B();return `<div class="gov"><div class="card govmain"><div class="smallcaps">HUMAN-IN-THE-LOOP CONTROL</div><h2>Officer decision governance</h2><p class="small">ClearBid recommends and records. The authorized officer retains final authority.</p><div class="flow"><div class="flowbox">⚠<b>Risk flag</b><small>${b.level} · ${b.risk}/100</small></div><div>→</div><div class="flowbox">⚖<b>Officer decision</b><small>Approve · Query · Disqualify</small></div><div>→</div><div class="flowbox">▣<b>Audit</b><small>Action + justification + review</small></div></div><div class="toolbar"><small>${b.name}<br>AI recommendation: ${b.rec}</small><div class="actions"><button class="btn" onclick="record('RAISE QUERY')">Query</button><button class="btn redbtn" onclick="record('DISQUALIFY')">Disqualify</button><button class="btn primary" onclick="approve()">Approve</button></div></div></div><div class="card"><div class="head"><h2>Safeguards</h2></div>${[["Hard-flag override","Written justification required."],["Independent review","Override escalated for second-level review."],["Pattern monitoring","Repeated overrides can be surfaced."],["Audit trail","Actor, time, action and hash recorded."]].map(x=>`<div class="safety">✓ <b>${x[0]}</b><small>${x[1]}</small></div>`).join("")}</div></div>`}
function auditPage(){return `<div class="card"><div class="head"><div><div class="smallcaps">TRACEABILITY</div><h2>Audit Trail</h2><small>Consequential actions are attributable.</small></div>${pill("100% COVERAGE","low")}</div>${audit.map(x=>`<div class="auditrow"><div class="dot"></div><div><span>${x[0]} · ${x[1]}</span><b>${x[2]}</b><small>Record hash: ${x[3]}</small></div></div>`).join("")}</div>`}
function evidence(){let b=B(),m=document.createElement("div");m.className="modalbg";m.innerHTML=`<div class="modal"><button class="close" onclick="this.closest('.modalbg').remove()">×</button><div class="smallcaps">EXPLAINABLE EVIDENCE CHAIN</div><h2 style="font-size:15px">Why is ${b.name} ${b.level} risk?</h2>${b.flags.length?b.flags.map(f=>`<div class="ev">${pill(f.level)} <b>${f.title}</b><p>${f.reason}</p>${f.evidence.map(e=>`<small>✓ ${e}</small>`).join("")}</div>`).join(""):`<p class="small">No material risk indicators. Supporting checks are verified/clear.</p>`}<p style="font-size:8px;background:#f1f5f8;padding:8px">Risk indicators require human investigation. They are not automatic proof of fraud or collusion.</p></div>`;document.body.appendChild(m)}
function approve(){if(B().level==="HIGH"||B().compliance<75){let m=document.createElement("div");m.className="modalbg";m.innerHTML=`<div class="modal"><div class="smallcaps">CONTROLLED OVERRIDE</div><h2 style="font-size:15px">Written justification required</h2><p class="small">This bidder has a significant risk/compliance flag. Approval requires an officer rationale and independent review.</p><label>Officer justification</label><textarea id="justification" placeholder="Explain the evidence or rule basis..."></textarea><div class="modalfoot"><button class="btn" onclick="this.closest('.modalbg').remove()">Cancel</button><button class="btn primary" onclick="submitOverride(this)">Submit Override</button></div></div>`;document.body.appendChild(m)}else record("APPROVE")}
function submitOverride(btn){let t=document.getElementById("justification").value.trim();if(!t){alert("Written justification is mandatory.");return}audit.push(["NOW","OFFICER","APPROVE override: "+B().name,"override...hash"]);audit.push(["NOW","GOVERNANCE","Independent review triggered","review...hash"]);btn.closest(".modalbg").remove();go("audit")}
function record(a){audit.push(["NOW","OFFICER",a+": "+B().name,"decision...hash"]);go("audit")}
function ruleAction(a){audit.push(["NOW","ADMIN",a+" rule RU-017","rule...hash"]);render()}
function render(){
  let body=page==="select"?tenderCards():page==="dashboard"?dashboard():page==="intake"?intake():page==="verification"?verification():page==="fraud"?fraud():page==="graph"?graph():page==="rules"?rules():page==="governance"?governance():auditPage();
  app.innerHTML=`<div class="app">${sidebar()}<main class="main">${portalTop()}${header()}${body}</main></div>`;
}
function processDemo(){let x=document.getElementById("processMsg");if(x)x.textContent="✓ Tender requirements normalized. Ready for verification."}
render();
setInterval(()=>{if(page==="dashboard"){const a=document.querySelector(".hero-slide.active");if(!a)return;const slides=[...document.querySelectorAll(".hero-slide")];const i=slides.indexOf(a);heroSlide((i+1)%slides.length)}},6000);
